INSERT INTO USER (USERNAME, PASSWORD, ROLE) VALUES ('sparky', '$2a$12$i9G6XPAWpM.ytEZ.EDgIjuoqeVrAyNP63HeGaLLJ4XSS/foKbPQF.', 'ADMIN');
INSERT INTO USER (USERNAME, PASSWORD, ROLE) VALUES ('user_1', '$2a$12$2mYmGFcyr7LaDwC8wXRUfeB1RIfgFb4XR9nSvX.B0otan01.HYWAe', 'USER');
INSERT INTO USER (USERNAME, PASSWORD, ROLE) VALUES ('user_2', '$2a$12$l8CW68jWTdi2fA/aFbV71Oau8sMw1SWGdX4zR7CxapoRa6LuKU7ZW', 'USER');

INSERT INTO TASK (TASK_NAME, TASK_DESCRIPTION, TASK_PRIORITY) VALUES ('Clean Bathroom', 'Scrub sink, toilet, shower, mirrors, and floors',2);
INSERT INTO TASK (TASK_NAME, TASK_DESCRIPTION, TASK_PRIORITY) VALUES ('Wash Dishes', 'Wash the dishes',4);
INSERT INTO TASK (TASK_NAME, TASK_DESCRIPTION, TASK_PRIORITY) VALUES ('Mow the  Front Lawn', 'Mow the front lawn.',2);
INSERT INTO TASK (TASK_NAME, TASK_DESCRIPTION, TASK_PRIORITY) VALUES ('Mow the  Back Lawn', 'Mow the back lawn.',2);

INSERT INTO DUTIES (OWNER_ID, TASK_ID) VALUES (2,1);
INSERT INTO DUTIES (OWNER_ID, TASK_ID) VALUES (2,3);
INSERT INTO DUTIES (OWNER_ID, TASK_ID) VALUES (3,2);
INSERT INTO DUTIES (OWNER_ID, TASK_ID) VALUES (3,4);