CREATE TABLE USER (
  USER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  USERNAME VARCHAR(128) NOT NULL UNIQUE,
  PASSWORD VARCHAR(256) NOT NULL,
  ROLE VARCHAR(128) NOT NULL
);

CREATE TABLE TASK (
    TASK_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TASK_NAME VARCHAR(128) NOT NULL,
    TASK_DESCRIPTION VARCHAR(256) NOT NULL,
    TASK_PRIORITY BIGINT NOT NULL
);

CREATE TABLE DUTIES (
    DUTY_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    OWNER_ID BIGINT NOT NULL,
    TASK_ID BIGINT NOT NULL
);